### ISSUE TITLE
BloomFilter.contains(..): redisKey is not defined

### ISSUE THREAD

**Issue by sufferingtrout** [chendotjs/bloomfilter-redis#2]
BloomFilter.contains(..) fails due to the 'redisKey' being out of scope when referenced by:``` this.redisClient.getbit(redisKey,...)```.

ReferenceError: redisKey is not defined
    at f (index.js:103:33)

The test case that tests this method masks the problem because it does not return the Promise from the test method.

**Comment by chendotjs** [comment]
Thanks so much. I'll close this issue.
