### ISSUE TITLE
Can BF be used without init to maintain existing data structure?

### ISSUE THREAD

**Issue by PWAckerman** [chendotjs/bloomfilter-redis#4]
Not really an issue, but a question. I want to use your bloom filter across many node.js processes, but I may be starting these processes many times. I'm assuming the initialization method overwrites the existing structure in Redis; can I use the instance without invoking the initialization method to maintain the existing structure, as long as the key stays constant?

**Comment by chendotjs** [comment]
Yes, the initialization method just creates storage structure in redis, to be more exact, a [redis string](https://redis.io/topics/data-types#strings). As long as the redis string exists, you can invoke `add` and `contains` method.

**Comment by alexdrans** [comment]
@chendotjs Ooh interesting. What's the common pattern then, manually check for the string in redis, and init if necessary? Perhaps it would be a good idea to use existing structures by default, and require a flag to force the operation to overwrite?

```javascript
new Bloomfilter({
  ...
  forceInit: true
}) 
```
